config/routes.rb
Rails.application.routes.draw do
  devise_for :freelancers
  devise_for :customers

  root to: 'pages#index'

  get 'pages/index'
  get 'pages/login'
  get 'pages/sign_up'

  resource :freelancer_profile, only: %i[edit update], controller: :freelancer_profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < User
end

app/models/freelancer.rb
class Freelancer < User
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, :last_name, presence: true

  self.inheritance_column = :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery
  devise_group :user, contains: [:freelancer , :customer]
end

app/controllers/freelancer_profile_controller.rb
class FreelancerProfileController < ApplicationController
  before_action :set_user

  def edit

  end

  def update
    if @user.update(profile_params)
      redirect_to edit_freelancer_profile_path, notice: 'Profile was successfully updated'
    else
      flash.now[:alert] = 'Please review the problems below:'
      render :edit
    end
  end

  private

  def profile_params
    params.require(:freelancer).permit(:first_name, :last_name, :location, :description)
  end

  def set_user
    @user = current_user
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end

  def login; end

  def sign_up; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(text)
    content_for :title, text
  end
end

app/views/freelancer_profile/edit.html.slim
- title = 'Edit profile'
- page_title title

h1= title

= simple_form_for @user, url: freelancer_profile_path do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :location
  = f.input :description
  = f.button :submit, 'Save'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = yield(:title) + ' | ' if content_for?(:title)
      | UpFree
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
      .container
        = link_to 'UpFree', root_path, class: 'navbar-brand'
        button.navbar-toggler aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarsExampleDefault" data-toggle="collapse" type="button"
          span.navbar-toggler-icon
        .collapse.navbar-collapse
          ul.navbar-nav.mr-auto
            li.nav-item.active
              a.nav-link href="#" Jobs

          ul.navbar-nav
            - if user_signed_in?
              li.nav-item.dropdown
                a#dropdown-nav.nav-link.active.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#"= current_user.email
                .dropdown-menu aria-labelledby="dropdown-nav"
                  h6.dropdown-header = current_user.role
                  .dropdown-divider
                  - if freelancer_signed_in?
                    = link_to 'Profile', edit_freelancer_profile_path, class: 'dropdown-item'
                    = link_to 'Edit password', edit_freelancer_registration_path, class: 'dropdown-item'
                  - else
                    = link_to 'Edit password', edit_customer_registration_path, class: 'dropdown-item'
                  .dropdown-divider
                  = link_to 'Logout', destroy_freelancer_session_path, method: :delete, class: 'dropdown-item'
            - else
              li.nav-item
                = link_to 'Log in', pages_login_path, class: 'nav-link active'
              li.nav-item
                = link_to 'Sign up', pages_sign_up_path, class: 'nav-link active'

    main role='main'
      .container
        - if notice
          p.alert.alert-success= notice
        - if alert
          p.alert.alert-danger= alert

        = yield

        hr
        footer.container
          p &copy UpFree 2018

app/views/pages/index.html.slim
.jumbotron.text-center
  .container
    h1.display-3 How it works
    p Post a job to tell us about your project. We'll quickly match you with the right freelancers.
.container
  .row
    .col-md-4
      h2 Hire
      p Browse profiles, reviews, and proposals then interview top candidates. Hire a favorite and begin your project.
    .col-md-4
      h2 Work
      p Use the Upwork platform to chat, share files, and collaborate from your desktop or on the go.
    .col-md-4
      h2 Pay
      p Invoicing and payments happen through Upwork. With Upwork Protection, only pay for work you authorize.

app/views/pages/login.html.slim
h1 Log in
h5 Select your role:

= link_to new_freelancer_session_path do
  button.btn.btn-success type='button' Freelancer
= link_to new_customer_session_path do
  button.btn.btn-info.ml-3 type='button' Customer

app/views/pages/sign_up.html.slim
h1 Sign up
h5 Select your role:

= link_to new_freelancer_registration_path do
  button.btn.btn-success type='button' Freelancer
= link_to new_customer_registration_path do
  button.btn.btn-info.ml-3 type='button' Customer